name: Cvedb Client

on:
  workflow_dispatch:

jobs:
  execute-workflow:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out
      uses: actions/checkout@main

    - name: Set GitHub Token
      run: |
        echo "$SSH_KEY" > id_rsa
      env:
        SSH_KEY: ${{secrets.SSH_KEY}}

    - name: Cvedb Execute
      id: cvedb
      uses: cvedb/action@main
      env:
        CVEDB_TOKEN: "${{ secrets.CVEDB_TOKEN }}"
      with:
        workflow: "Github Recon & Scanner"
        space: "Github Recon & Scanner"
        project: "Base Project"
        create_structure: true
        config_path: config.yaml
